
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = proxy_rpc_client
SERVER = proxy_rpc_server

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = proxy_rpc.x

TARGETS_SVC.c = proxy_rpc_svc.c proxy_rpc_server.c proxy_rpc_xdr.c 
TARGETS_CLNT.c = proxy_rpc_clnt.c proxy_rpc_client.c proxy_rpc_xdr.c 
TARGETS = proxy_rpc.h proxy_rpc_xdr.c proxy_rpc_clnt.c proxy_rpc_svc.c proxy_rpc_client.c proxy_rpc_server.c

# Compiler flags 
CC = gcc

LDLIBS += -lresolv -lnsl -lcurl


# Targets 

all : $(CLIENT) $(SERVER)





$(CLIENT) : $(OBJECTS_CLNT) 
	$(CC) -o $(CLIENT) $(TARGETS_CLNT.c) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(CC) -o $(SERVER) $(TARGETS_SVC.c) $(LDLIBS)

 clean:
	 $(RM) core $(CLIENT) $(SERVER)

