/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proxy_rpc.h"

int main(int argc, char** argv)
{
	CLIENT *clnt;
	proxy_rpc_out  *result;
	proxy_rpc_in  url;

	if(argc != 3){
		printf("usage: proxy_rpc_client <hostname> <url>\n");
        	exit(1);
	}
#ifndef	DEBUG
	clnt = clnt_create (argv[1], PROXY_RPC_PROG, PROXY_RPC_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (argv[1]);
		exit (1);
	}
#endif	/* DEBUG */
	url.arg = argv[2];
	result = proxy_rpc_proc_1(&url, clnt);
	if (result == (proxy_rpc_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("result:\n%s\n",result->res);
		printf("length:%d\n",result->len);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


