/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "proxy_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

proxy_rpc_out *
proxy_rpc_proc_1(proxy_rpc_in *argp, CLIENT *clnt)
{
	static proxy_rpc_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PROXY_RPC_PROC,
		(xdrproc_t) xdr_proxy_rpc_in, (caddr_t) argp,
		(xdrproc_t) xdr_proxy_rpc_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
