/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROXY_RPC_H_RPCGEN
#define _PROXY_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct proxy_rpc_in {
	char *arg;
};
typedef struct proxy_rpc_in proxy_rpc_in;

struct proxy_rpc_out {
	int len;
	char *res;
};
typedef struct proxy_rpc_out proxy_rpc_out;

#define PROXY_RPC_PROG 0x23450000
#define PROXY_RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROXY_RPC_PROC 1
extern  proxy_rpc_out * proxy_rpc_proc_1(proxy_rpc_in *, CLIENT *);
extern  proxy_rpc_out * proxy_rpc_proc_1_svc(proxy_rpc_in *, struct svc_req *);
extern int proxy_rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROXY_RPC_PROC 1
extern  proxy_rpc_out * proxy_rpc_proc_1();
extern  proxy_rpc_out * proxy_rpc_proc_1_svc();
extern int proxy_rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_proxy_rpc_in (XDR *, proxy_rpc_in*);
extern  bool_t xdr_proxy_rpc_out (XDR *, proxy_rpc_out*);

#else /* K&R C */
extern bool_t xdr_proxy_rpc_in ();
extern bool_t xdr_proxy_rpc_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROXY_RPC_H_RPCGEN */
